# Generated by Django 3.1.4 on 2021-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20210406_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
