# Generated by Django 3.1.4 on 2021-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20210407_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
    ]
