# Generated by Django 3.1.4 on 2021-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_paper_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
