# Generated by Django 3.1.4 on 2021-04-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20210407_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='title',
        ),
    ]
