# Generated by Django 3.1.4 on 2021-04-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientificjournal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Published_Paper',
        ),
    ]
