# Generated by Django 3.1.4 on 2021-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientificjournal', '0002_auto_20210406_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published_paper',
            name='image',
            field=models.FileField(upload_to='pics'),
        ),
    ]
