# Generated by Django 3.1.4 on 2021-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientificjournal', '0003_auto_20210407_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='published_paper',
            name='file',
            field=models.FileField(default=1, upload_to='fiile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='published_paper',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
